export const MARKER_LABELS: Record<string, string> = {
  fastingGlucose: 'Fasting Glucose',
  hba1c: 'HbA1c',
  fastingInsulin: 'Fasting Insulin',
  triglycerides: 'Triglycerides',
  hdl: 'HDL Cholesterol',
  apob: 'ApoB',
  hscrp: 'hs-CRP',
  alt: 'ALT',
  ast: 'AST',
  ggt: 'GGT',
  egfr: 'eGFR',
  creatinine: 'Creatinine',
  cystatinC: 'Cystatin C',
  bun: 'BUN',
  uricAcid: 'Uric Acid',
  uacr: 'UACR',
  alkalinePhosphatase: 'Alkaline Phosphatase',
  totalBilirubin: 'Total Bilirubin',
  systolicBP: 'Systolic BP',
  diastolicBP: 'Diastolic BP',
  restingHR: 'Resting Heart Rate',
  hrv: 'Heart Rate Variability',
  vo2max: 'VO2 Max',
  homocysteine: 'Homocysteine',
  lpa: 'Lp(a)',
  fibrinogen: 'Fibrinogen',
  ntprobnp: 'NT-proBNP',
  cac: 'Coronary Calcium Score',
  totalTestosterone: 'Total Testosterone',
  freeTestosterone: 'Free Testosterone',
  shbg: 'SHBG',
  dheas: 'DHEA-S',
  igf1: 'IGF-1',
  estradiolMale: 'Estradiol',
  prolactin: 'Prolactin',
  estradiolFemale: 'Estradiol',
  progesterone: 'Progesterone',
  fsh: 'FSH',
  lh: 'LH',
  testosteroneFemale: 'Testosterone',
  tsh: 'TSH',
  freeT3: 'Free T3',
  freeT4: 'Free T4',
  reverseT3: 'Reverse T3',
  tpoAntibodies: 'TPO Antibodies',
  cortisolAM: 'Morning Cortisol',
  il6: 'IL-6',
  ferritin: 'Ferritin',
  esr: 'ESR',
  vitaminD: 'Vitamin D',
  vitaminB12: 'Vitamin B12',
  rbcMagnesium: 'RBC Magnesium',
  omega3Index: 'Omega-3 Index',
  coq10: 'CoQ10',
  nad: 'NAD+',
  zinc: 'Zinc',
  wbc: 'WBC',
  mcv: 'MCV',
  folate: 'Folate',
  dunedinPace: 'DunedinPACE',
  grimAgeAccel: 'GrimAge Acceleration',
  telomerePercentile: 'Telomere Percentile',
};
