import type { IntakeSection } from '../types';

export const INTAKE_SECTIONS: IntakeSection[] = [
  // ── 1. PERSONAL PROFILE ────────────────────────────────────────────────
  {
    id: 'personal',
    icon: '◈',
    title: 'Personal Profile',
    subtitle: 'Foundational data to anchor your BioAge assessment',
    questions: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name' },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name' },
      { id: 'dob', label: 'Date of Birth', type: 'date' },
      {
        id: 'sex',
        label: 'Biological Sex',
        type: 'select',
        options: [
          { value: 'Male', label: 'Male' },
          { value: 'Female', label: 'Female' },
        ],
      },
      {
        id: 'ethnicity',
        label: 'Ethnicity (used for age-adjusted reference ranges)',
        type: 'select',
        options: [
          { value: 'White / Caucasian', label: 'White / Caucasian' },
          { value: 'Black / African American', label: 'Black / African American' },
          { value: 'Hispanic / Latino', label: 'Hispanic / Latino' },
          { value: 'Asian', label: 'Asian' },
          { value: 'South Asian', label: 'South Asian' },
          { value: 'Middle Eastern', label: 'Middle Eastern' },
          { value: 'Mixed / Multiracial', label: 'Mixed / Multiracial' },
          { value: 'Prefer not to say', label: 'Prefer not to say' },
        ],
      },
      { id: 'height', label: 'Height (inches)', type: 'number', placeholder: 'e.g. 70' },
      { id: 'weight', label: 'Current Weight (lbs)', type: 'number', placeholder: 'e.g. 180' },
      { id: 'waist', label: 'Waist Circumference (inches)', type: 'number', placeholder: 'e.g. 34' },
      { id: 'hip', label: 'Hip Circumference (inches)', type: 'number', placeholder: 'e.g. 38' },
    ],
  },

  // ── 2. IN-PERSON BIOMETRICS ────────────────────────────────────────────
  {
    id: 'biometric',
    icon: '◆',
    title: 'In-Person Biometrics',
    subtitle: 'Nurse-administered measurements captured during your visit',
    questions: [
      {
        id: 'bioNote',
        type: 'info',
        label:
          'The following fields are completed by your BR clinical provider during your in-person or mobile visit. If completing digitally in advance, leave blank.',
      },
      { id: 'biaBodyFat', label: 'BIA — Body Fat Percentage (%)', type: 'number', placeholder: 'e.g. 22.5', nurseField: true },
      { id: 'biaVisceralFat', label: 'BIA — Visceral Fat Rating (1–30 scale)', type: 'number', placeholder: 'e.g. 8', nurseField: true },
      { id: 'biaSkelMuscle', label: 'BIA — Skeletal Muscle Mass (lbs)', type: 'number', placeholder: 'e.g. 95', nurseField: true },
      { id: 'biaTotalWater', label: 'BIA — Total Body Water (%)', type: 'number', placeholder: 'e.g. 58', nurseField: true },
      { id: 'ymcaHR', label: 'YMCA Step Test — Recovery Heart Rate (bpm at 1 min post)', type: 'number', placeholder: 'e.g. 92', nurseField: true },
      { id: 'ymcaVO2', label: 'YMCA Step Test — Estimated VO2 Max (mL/kg/min)', type: 'number', placeholder: 'Calculated by provider', nurseField: true },
      { id: 'gripStrengthDom', label: 'Grip Strength — Dominant Hand (kg)', type: 'number', placeholder: 'e.g. 42', nurseField: true },
      { id: 'gripStrengthNon', label: 'Grip Strength — Non-Dominant Hand (kg)', type: 'number', placeholder: 'e.g. 38', nurseField: true },
      { id: 'nurseSpO2', label: 'Resting SpO2 (%)', type: 'number', placeholder: 'e.g. 98', nurseField: true },
      { id: 'nurseBPSys', label: 'Blood Pressure — Systolic (mmHg)', type: 'number', placeholder: 'e.g. 118', nurseField: true },
      { id: 'nurseBPDia', label: 'Blood Pressure — Diastolic (mmHg)', type: 'number', placeholder: 'e.g. 76', nurseField: true },
      { id: 'nurseRestingHR', label: 'Resting Heart Rate (bpm)', type: 'number', placeholder: 'e.g. 62', nurseField: true },
    ],
  },

  // ── 3. MEDICAL HISTORY ─────────────────────────────────────────────────
  {
    id: 'medHistory',
    icon: '✦',
    title: 'Medical History',
    subtitle: 'Critical context — identical labs carry different risk in different bodies',
    questions: [
      {
        id: 'medConditions',
        label: 'Have you ever been diagnosed with any of the following? (Select all that apply)',
        type: 'multiselect',
        options: [
          { value: 'Cardiovascular disease (heart attack, stent, bypass, heart failure)', label: 'Cardiovascular disease (heart attack, stent, bypass, heart failure)' },
          { value: 'Stroke or TIA', label: 'Stroke or TIA' },
          { value: 'Hypertension (high blood pressure)', label: 'Hypertension (high blood pressure)' },
          { value: 'Hyperlipidemia (high cholesterol)', label: 'Hyperlipidemia (high cholesterol)' },
          { value: 'Type 2 diabetes', label: 'Type 2 diabetes' },
          { value: 'Prediabetes', label: 'Prediabetes' },
          { value: 'Type 1 diabetes', label: 'Type 1 diabetes' },
          { value: 'Thyroid disease (hypo or hyperthyroid)', label: 'Thyroid disease (hypo or hyperthyroid)' },
          { value: 'Autoimmune disease', label: 'Autoimmune disease' },
          { value: 'Kidney disease (CKD or other)', label: 'Kidney disease (CKD or other)' },
          { value: 'Liver disease (fatty liver, cirrhosis, hepatitis)', label: 'Liver disease (fatty liver, cirrhosis, hepatitis)' },
          { value: 'Obstructive sleep apnea', label: 'Obstructive sleep apnea' },
          { value: 'Osteoporosis or osteopenia', label: 'Osteoporosis or osteopenia' },
          { value: 'Depression', label: 'Depression' },
          { value: 'Anxiety disorder', label: 'Anxiety disorder' },
          { value: 'Chronic pain condition', label: 'Chronic pain condition' },
          { value: 'Inflammatory bowel disease (Crohn\'s, UC)', label: 'Inflammatory bowel disease (Crohn\'s, UC)' },
          { value: 'GERD / acid reflux (chronic)', label: 'GERD / acid reflux (chronic)' },
          { value: 'Atrial fibrillation or arrhythmia', label: 'Atrial fibrillation or arrhythmia' },
          { value: 'None of the above', label: 'None of the above' },
        ],
        riskMap: {
          'Cardiovascular disease (heart attack, stent, bypass, heart failure)': 3,
          'Stroke or TIA': 2.5,
          'Hypertension (high blood pressure)': 1.5,
          'Hyperlipidemia (high cholesterol)': 1,
          'Type 2 diabetes': 2.5,
          'Prediabetes': 1.5,
          'Type 1 diabetes': 2,
          'Thyroid disease (hypo or hyperthyroid)': 1,
          'Autoimmune disease': 1.5,
          'Kidney disease (CKD or other)': 2,
          'Liver disease (fatty liver, cirrhosis, hepatitis)': 2,
          'Obstructive sleep apnea': 1.5,
          'Osteoporosis or osteopenia': 1,
          'Depression': 1,
          'Anxiety disorder': 0.5,
          'Chronic pain condition': 1,
          'Inflammatory bowel disease (Crohn\'s, UC)': 1.5,
          'GERD / acid reflux (chronic)': 0.5,
          'Atrial fibrillation or arrhythmia': 2,
        },
      },
      {
        id: 'currentMedCount',
        label: 'Number of current prescription medications',
        type: 'radio',
        options: [
          { label: 'None', value: 0, risk: 0 },
          { label: '1–2 medications', value: 1, risk: 0.5 },
          { label: '3–5 medications', value: 2, risk: 1 },
          { label: '6+ medications (polypharmacy)', value: 3, risk: 2 },
        ],
      },
      {
        id: 'priorSurgeries',
        label: 'Significant surgeries or hospitalizations in the last 5 years (optional)',
        type: 'textarea',
        placeholder: 'e.g. Appendectomy 2022, cardiac catheterization 2023...',
      },
      {
        id: 'allergies',
        label: 'Known drug or supplement allergies',
        type: 'text',
        placeholder: 'e.g. Penicillin, sulfa drugs, none known',
      },
    ],
  },

  // ── 4. CANCER HISTORY & SCREENING ─────────────────────────────────────
  {
    id: 'cancer',
    icon: '◉',
    title: 'Cancer History & Screening',
    subtitle: 'Personal history, treatment context, and preventive screening compliance',
    questions: [
      {
        id: 'cancerPersonal',
        label: 'Have you ever been diagnosed with cancer?',
        type: 'radio',
        options: [
          { label: 'No — never diagnosed', value: 'no', risk: 0 },
          { label: 'Yes — currently in active treatment', value: 'active', risk: 3 },
          { label: 'Yes — in remission, less than 2 years', value: 'remission2', risk: 2 },
          { label: 'Yes — in remission, 2–5 years', value: 'remission5', risk: 1 },
          { label: 'Yes — in remission or cured, 5+ years', value: 'remission5plus', risk: 0.5 },
        ],
      },
      {
        id: 'cancerType',
        label: 'If yes — cancer type(s) (select all that apply)',
        type: 'multiselect',
        options: [
          { value: 'Breast', label: 'Breast' },
          { value: 'Prostate', label: 'Prostate' },
          { value: 'Colorectal', label: 'Colorectal' },
          { value: 'Lung', label: 'Lung' },
          { value: 'Melanoma / Skin', label: 'Melanoma / Skin' },
          { value: 'Thyroid', label: 'Thyroid' },
          { value: 'Bladder', label: 'Bladder' },
          { value: 'Kidney', label: 'Kidney' },
          { value: 'Pancreatic', label: 'Pancreatic' },
          { value: 'Ovarian', label: 'Ovarian' },
          { value: 'Cervical', label: 'Cervical' },
          { value: 'Testicular', label: 'Testicular' },
          { value: 'Lymphoma', label: 'Lymphoma' },
          { value: 'Leukemia', label: 'Leukemia' },
          { value: 'Brain / CNS', label: 'Brain / CNS' },
          { value: 'Head and neck', label: 'Head and neck' },
          { value: 'Other', label: 'Other' },
          { value: 'Not applicable', label: 'Not applicable' },
        ],
      },
      {
        id: 'cancerTreatment',
        label: 'If yes — treatment(s) received (select all that apply)',
        type: 'multiselect',
        options: [
          { value: 'Surgery only', label: 'Surgery only' },
          { value: 'Chemotherapy', label: 'Chemotherapy' },
          { value: 'Radiation therapy', label: 'Radiation therapy' },
          { value: 'Immunotherapy / checkpoint inhibitors', label: 'Immunotherapy / checkpoint inhibitors' },
          { value: 'Hormone therapy (e.g. tamoxifen, ADT)', label: 'Hormone therapy (e.g. tamoxifen, ADT)' },
          { value: 'Targeted therapy', label: 'Targeted therapy' },
          { value: 'Stem cell / bone marrow transplant', label: 'Stem cell / bone marrow transplant' },
          { value: 'Combination of the above', label: 'Combination of the above' },
          { value: 'Not applicable', label: 'Not applicable' },
        ],
        riskMap: {
          'Chemotherapy': 1.5,
          'Radiation therapy': 1,
          'Immunotherapy / checkpoint inhibitors': 0.8,
          'Hormone therapy (e.g. tamoxifen, ADT)': 0.8,
          'Stem cell / bone marrow transplant': 2,
        },
      },
      {
        id: 'cancerSurveillance',
        label: 'Are you currently under oncology surveillance or follow-up?',
        type: 'radio',
        options: [
          { label: 'Yes — active monitoring with oncologist', value: 'yes', risk: 0 },
          { label: 'No — discharged from oncology care', value: 'no', risk: 0 },
          { label: 'Not applicable — no cancer history', value: 'na', risk: 0 },
        ],
      },
      {
        id: 'colonoscopy',
        label: 'Most recent colonoscopy (if age 45+ or at elevated risk)',
        type: 'radio',
        options: [
          { label: 'Within the last 5 years — normal', value: 'recent_normal', risk: 0 },
          { label: 'Within the last 5 years — polyps found', value: 'recent_polyps', risk: 0.8 },
          { label: '6–10 years ago', value: '6to10', risk: 0.5 },
          { label: 'Over 10 years ago or never (age 45+)', value: 'overdue', risk: 1.5 },
          { label: 'Not yet due (under 45, no elevated risk)', value: 'notdue', risk: 0 },
        ],
      },
      {
        id: 'psaTest',
        label: '[Male] Most recent PSA test',
        type: 'radio',
        sexFilter: 'Male',
        options: [
          { label: 'Within the last year — normal', value: 'recent_normal', risk: 0 },
          { label: 'Within the last year — elevated, under investigation', value: 'elevated', risk: 1 },
          { label: '1–3 years ago', value: '1to3', risk: 0.3 },
          { label: 'Never tested (age 40+)', value: 'never', risk: 0.5 },
          { label: 'Not applicable / under 40', value: 'na', risk: 0 },
        ],
      },
      {
        id: 'skinChecks',
        label: 'Dermatology skin checks — frequency',
        type: 'radio',
        options: [
          { label: 'Annually with dermatologist', value: 'annual', risk: 0 },
          { label: 'Every 2–3 years', value: '2to3', risk: 0.3 },
          { label: 'Rarely or never', value: 'rare', risk: 0.8 },
        ],
      },
      {
        id: 'ldctScan',
        label: 'Low-dose CT lung cancer screening (for former/current smokers, age 50–80)',
        type: 'radio',
        options: [
          { label: 'Up to date — completed within recommended interval', value: 'current', risk: 0 },
          { label: 'Overdue — haven\'t completed despite eligibility', value: 'overdue', risk: 1 },
          { label: 'Not eligible — never smoked or outside age range', value: 'na', risk: 0 },
        ],
      },
    ],
  },

  // ── 5. FAMILY HISTORY ─────────────────────────────────────────────────
  {
    id: 'familyHistory',
    icon: '◐',
    title: 'Family History',
    subtitle: 'Hereditary risk is a legitimate and quantifiable aging accelerant',
    questions: [
      {
        id: 'familyHeartDisease',
        label: 'Family history of early heart disease (before age 60, first-degree relative)?',
        type: 'radio',
        options: [
          { label: 'No', value: 0, risk: 0 },
          { label: 'Yes — one relative', value: 1, risk: 1.5 },
          { label: 'Yes — multiple relatives', value: 2, risk: 2.5 },
          { label: 'Unknown', value: 3, risk: 0.5 },
        ],
      },
      {
        id: 'familyDementia',
        label: 'Family history of dementia or Alzheimer\'s disease?',
        type: 'radio',
        options: [
          { label: 'No', value: 0, risk: 0 },
          { label: 'Yes — one relative', value: 1, risk: 1 },
          { label: 'Yes — multiple relatives', value: 2, risk: 2 },
          { label: 'Unknown', value: 3, risk: 0.3 },
        ],
      },
      {
        id: 'familyDiabetes',
        label: 'Family history of type 2 diabetes?',
        type: 'radio',
        options: [
          { label: 'No', value: 0, risk: 0 },
          { label: 'Yes — one parent or sibling', value: 1, risk: 1 },
          { label: 'Yes — both parents or multiple siblings', value: 2, risk: 2 },
          { label: 'Unknown', value: 3, risk: 0.3 },
        ],
      },
      {
        id: 'familyCancer',
        label: 'Family history of cancer — first-degree relative?',
        type: 'radio',
        options: [
          { label: 'No', value: 0, risk: 0 },
          { label: 'Yes — one relative', value: 1, risk: 0.8 },
          { label: 'Yes — multiple relatives or hereditary syndrome (BRCA, Lynch, etc.)', value: 2, risk: 2 },
          { label: 'Unknown', value: 3, risk: 0.3 },
        ],
      },
      {
        id: 'familyLongevity',
        label: 'First-degree relatives who lived past 90 in good health?',
        type: 'radio',
        options: [
          { label: 'Yes — one or more', value: 2, risk: -1 },
          { label: 'Some lived into their 80s in good health', value: 1, risk: -0.5 },
          { label: 'No — most had significant illness before 75', value: 0, risk: 0.5 },
          { label: 'Unknown', value: 3, risk: 0 },
        ],
      },
    ],
  },

  // ── 6. MEDICATIONS ─────────────────────────────────────────────────────
  {
    id: 'medications',
    icon: '◎',
    title: 'Medications',
    subtitle: 'Structured medication context — some drugs deplete key longevity nutrients',
    questions: [
      {
        id: 'medNote',
        type: 'info',
        label:
          'Select any medications you currently take. This helps us identify nutrient depletions and interpret your biomarkers correctly. This does not affect your BioAge score negatively — it provides clinical context.',
      },
      {
        id: 'medList',
        label: 'Current medications — select all that apply',
        type: 'multiselect',
        options: [
          { value: 'Statin (Atorvastatin / Rosuvastatin / Simvastatin)', label: 'Statin (Atorvastatin / Rosuvastatin / Simvastatin)' },
          { value: 'Metformin (diabetes / blood sugar)', label: 'Metformin (diabetes / blood sugar)' },
          { value: 'GLP-1 agonist (Semaglutide / Ozempic / Wegovy / Tirzepatide)', label: 'GLP-1 agonist (Semaglutide / Ozempic / Wegovy / Tirzepatide)' },
          { value: 'ACE inhibitor / ARB (Lisinopril / Losartan — blood pressure)', label: 'ACE inhibitor / ARB (Lisinopril / Losartan — blood pressure)' },
          { value: 'Beta blocker (Metoprolol / Atenolol — heart rate / BP)', label: 'Beta blocker (Metoprolol / Atenolol — heart rate / BP)' },
          { value: 'Calcium channel blocker (Amlodipine — blood pressure)', label: 'Calcium channel blocker (Amlodipine — blood pressure)' },
          { value: 'Diuretic (Hydrochlorothiazide / Furosemide)', label: 'Diuretic (Hydrochlorothiazide / Furosemide)' },
          { value: 'Levothyroxine / Synthroid (thyroid)', label: 'Levothyroxine / Synthroid (thyroid)' },
          { value: 'PPI / Proton pump inhibitor (Omeprazole / Pantoprazole — stomach)', label: 'PPI / Proton pump inhibitor (Omeprazole / Pantoprazole — stomach)' },
          { value: 'H2 blocker (Famotidine / Pepcid — stomach)', label: 'H2 blocker (Famotidine / Pepcid — stomach)' },
          { value: 'SSRI (Sertraline / Escitalopram / Fluoxetine — mood)', label: 'SSRI (Sertraline / Escitalopram / Fluoxetine — mood)' },
          { value: 'SNRI (Duloxetine / Venlafaxine — mood / pain)', label: 'SNRI (Duloxetine / Venlafaxine — mood / pain)' },
          { value: 'Bupropion (Wellbutrin)', label: 'Bupropion (Wellbutrin)' },
          { value: 'Benzodiazepine (Xanax / Klonopin / Ativan)', label: 'Benzodiazepine (Xanax / Klonopin / Ativan)' },
          { value: 'Sleep medication (Ambien / Lunesta / Trazodone)', label: 'Sleep medication (Ambien / Lunesta / Trazodone)' },
          { value: 'NSAID / Anti-inflammatory (Ibuprofen / Naproxen — regular use)', label: 'NSAID / Anti-inflammatory (Ibuprofen / Naproxen — regular use)' },
          { value: 'Aspirin (daily, cardiac)', label: 'Aspirin (daily, cardiac)' },
          { value: 'Blood thinner (Eliquis / Warfarin / Xarelto)', label: 'Blood thinner (Eliquis / Warfarin / Xarelto)' },
          { value: 'Testosterone / HRT (prescription)', label: 'Testosterone / HRT (prescription)' },
          { value: 'Oral contraceptive or hormonal IUD', label: 'Oral contraceptive or hormonal IUD' },
          { value: 'Corticosteroid (Prednisone — regular use)', label: 'Corticosteroid (Prednisone — regular use)' },
          { value: 'Finasteride / Dutasteride (hair / prostate)', label: 'Finasteride / Dutasteride (hair / prostate)' },
          { value: 'Erectile dysfunction medication (Sildenafil / Tadalafil)', label: 'Erectile dysfunction medication (Sildenafil / Tadalafil)' },
          { value: 'Immunosuppressant (post-transplant or autoimmune)', label: 'Immunosuppressant (post-transplant or autoimmune)' },
          { value: 'None of the above', label: 'None of the above' },
        ],
      },
      {
        id: 'medicationNotes',
        label: 'Any medications not listed above? (optional)',
        type: 'textarea',
        placeholder: 'List any additional medications with dose...',
      },
    ],
  },

  // ── 7. HORMONAL HEALTH ─────────────────────────────────────────────────
  {
    id: 'hormones',
    icon: '◇',
    title: 'Hormonal Health',
    subtitle: 'Sex-specific endocrine function — a primary driver of biological age',
    questions: [
      {
        id: 'hormoneSexNote',
        type: 'info',
        label:
          'The following questions are sex-specific and will display based on your biological sex. Both sections are clinically important — please answer honestly.',
      },
      // FEMALE
      {
        id: 'cycleRegularity',
        label: '[Female] Menstrual cycle regularity',
        type: 'radio',
        sexFilter: 'Female',
        options: [
          { label: 'Regular — consistent 24–35 day cycles', value: 4, risk: 0 },
          { label: 'Slightly irregular — varies by more than a week', value: 3, risk: 0.5 },
          { label: 'Significantly irregular or unpredictable', value: 2, risk: 1 },
          { label: 'Absent (amenorrhea) — not due to menopause', value: 1, risk: 1.5 },
          { label: 'Postmenopausal — no period for 12+ months', value: 0, risk: 0 },
        ],
      },
      {
        id: 'menopauseStatus',
        label: '[Female] Menopause / perimenopause status',
        type: 'radio',
        sexFilter: 'Female',
        options: [
          { label: 'Premenopausal — regular cycles', value: 0, risk: 0 },
          { label: 'Perimenopausal — irregular cycles, symptoms present', value: 1, risk: 0.5 },
          { label: 'Postmenopausal — natural', value: 2, risk: 0.5 },
          { label: 'Surgically menopausal (oophorectomy)', value: 3, risk: 1 },
          { label: 'On HRT / estrogen therapy', value: 4, risk: 0 },
        ],
      },
      {
        id: 'femaleSymptoms',
        label: '[Female] Current symptoms — select all that apply',
        type: 'multiselect',
        sexFilter: 'Female',
        options: [
          { value: 'Hot flashes', label: 'Hot flashes' },
          { value: 'Night sweats', label: 'Night sweats' },
          { value: 'Mood changes / irritability', label: 'Mood changes / irritability' },
          { value: 'Vaginal dryness', label: 'Vaginal dryness' },
          { value: 'Hair thinning or loss', label: 'Hair thinning or loss' },
          { value: 'Brain fog', label: 'Brain fog' },
          { value: 'Decreased libido', label: 'Decreased libido' },
          { value: 'Sleep disruption', label: 'Sleep disruption' },
          { value: 'Joint pain', label: 'Joint pain' },
          { value: 'None of the above', label: 'None of the above' },
        ],
        riskMap: {
          'Hot flashes': 0.5,
          'Night sweats': 0.5,
          'Mood changes / irritability': 0.3,
          'Vaginal dryness': 0.5,
          'Hair thinning or loss': 0.5,
          'Brain fog': 0.5,
          'Decreased libido': 0.3,
          'Sleep disruption': 0.5,
          'Joint pain': 0.3,
        },
      },
      {
        id: 'femaleHistory',
        label: '[Female] Reproductive history — select all that apply',
        type: 'multiselect',
        sexFilter: 'Female',
        options: [
          { value: 'History of PCOS', label: 'History of PCOS' },
          { value: 'History of endometriosis', label: 'History of endometriosis' },
          { value: 'History of infertility', label: 'History of infertility' },
          { value: 'History of recurrent miscarriage (2+)', label: 'History of recurrent miscarriage (2+)' },
          { value: 'Currently on hormonal contraceptives', label: 'Currently on hormonal contraceptives' },
          { value: 'History of postpartum depression', label: 'History of postpartum depression' },
          { value: 'None of the above', label: 'None of the above' },
        ],
        riskMap: {
          'History of PCOS': 1,
          'History of endometriosis': 0.8,
          'History of infertility': 0.5,
          'History of recurrent miscarriage (2+)': 0.5,
          'History of postpartum depression': 0.3,
        },
      },
      // MALE
      {
        id: 'morningErections',
        label: '[Male] Morning erections (nocturnal penile tumescence)',
        type: 'radio',
        sexFilter: 'Male',
        options: [
          { label: 'Daily or near-daily', value: 4, risk: 0 },
          { label: 'Several times per week', value: 3, risk: 0.3 },
          { label: 'Occasionally — a few times per month', value: 2, risk: 0.8 },
          { label: 'Rarely or never', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'erectileFunction',
        label: '[Male] Erectile function',
        type: 'radio',
        sexFilter: 'Male',
        options: [
          { label: 'No issues', value: 4, risk: 0 },
          { label: 'Mild difficulty — occasional', value: 3, risk: 0.5 },
          { label: 'Moderate difficulty — occurs more than half the time', value: 2, risk: 1.5 },
          { label: 'Significant difficulty — rarely able to achieve or maintain', value: 1, risk: 2.5 },
        ],
      },
      {
        id: 'maleSymptoms',
        label: '[Male] Current symptoms — select all that apply',
        type: 'multiselect',
        sexFilter: 'Male',
        options: [
          { value: 'Noticeable muscle loss despite training', label: 'Noticeable muscle loss despite training' },
          { value: 'Low motivation or drive', label: 'Low motivation or drive' },
          { value: 'Decreased libido', label: 'Decreased libido' },
          { value: 'Brain fog or difficulty concentrating', label: 'Brain fog or difficulty concentrating' },
          { value: 'Increased abdominal body fat', label: 'Increased abdominal body fat' },
          { value: 'Mood changes or irritability', label: 'Mood changes or irritability' },
          { value: 'Fatigue or low energy', label: 'Fatigue or low energy' },
          { value: 'Reduced strength', label: 'Reduced strength' },
          { value: 'Hair thinning', label: 'Hair thinning' },
          { value: 'None of the above', label: 'None of the above' },
        ],
        riskMap: {
          'Noticeable muscle loss despite training': 1,
          'Low motivation or drive': 0.5,
          'Decreased libido': 0.8,
          'Brain fog or difficulty concentrating': 0.5,
          'Increased abdominal body fat': 0.8,
          'Mood changes or irritability': 0.3,
          'Fatigue or low energy': 0.5,
          'Reduced strength': 0.8,
          'Hair thinning': 0.3,
        },
      },
      {
        id: 'urinaryFlow',
        label: '[Male] Urinary flow and function',
        type: 'radio',
        sexFilter: 'Male',
        options: [
          { label: 'Normal — strong stream, no hesitancy', value: 4, risk: 0 },
          { label: 'Mild hesitancy or slightly reduced flow', value: 3, risk: 0.5 },
          { label: 'Moderate difficulty initiating or weak stream', value: 2, risk: 1 },
          { label: 'Significant urinary difficulty — evaluated by physician', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'trtHistory',
        label: '[Male] Testosterone or hormonal medication history',
        type: 'radio',
        sexFilter: 'Male',
        options: [
          { label: 'Never used TRT or fertility medications', value: 0, risk: 0 },
          { label: 'Currently on prescribed TRT', value: 1, risk: 0 },
          { label: 'Previously on TRT, now off', value: 2, risk: 0.5 },
          { label: 'Currently on fertility medications (HCG, Clomid)', value: 3, risk: 0 },
          { label: 'History of anabolic steroid use (non-prescribed)', value: 4, risk: 1.5 },
        ],
      },
    ],
  },

  // ── 8. METABOLIC PROFILE ───────────────────────────────────────────────
  {
    id: 'metabolic',
    icon: '◈',
    title: 'Metabolic Profile',
    subtitle: 'Known values significantly accelerate your BioAge calculation',
    questions: [
      {
        id: 'knownHbA1c',
        label: 'Most recent HbA1c (if known)',
        type: 'radio',
        options: [
          { label: 'Under 5.3% — Optimal', value: 'optimal', risk: -0.5 },
          { label: '5.3–5.6% — Normal', value: 'normal', risk: 0 },
          { label: '5.7–6.4% — Prediabetes range', value: 'prediabetes', risk: 2 },
          { label: '6.5%+ — Diabetes range', value: 'diabetes', risk: 3 },
          { label: 'I don\'t know', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'knownFastingGlucose',
        label: 'Most recent fasting glucose (if known)',
        type: 'radio',
        options: [
          { label: 'Under 85 mg/dL — Optimal', value: 'optimal', risk: -0.3 },
          { label: '85–99 mg/dL — Normal', value: 'normal', risk: 0 },
          { label: '100–125 mg/dL — Impaired fasting', value: 'impaired', risk: 1.5 },
          { label: '126+ mg/dL — Diabetic range', value: 'diabetic', risk: 3 },
          { label: 'I don\'t know', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'knownInsulin',
        label: 'Most recent fasting insulin (if known)',
        type: 'radio',
        options: [
          { label: 'Under 5 µIU/mL — Optimal', value: 'optimal', risk: -0.5 },
          { label: '5–10 µIU/mL — Normal', value: 'normal', risk: 0 },
          { label: '10–20 µIU/mL — Insulin resistance range', value: 'elevated', risk: 2 },
          { label: '20+ µIU/mL — High', value: 'high', risk: 3 },
          { label: 'I don\'t know', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'knownTriglycerides',
        label: 'Most recent triglycerides (if known)',
        type: 'radio',
        options: [
          { label: 'Under 100 mg/dL — Optimal', value: 'optimal', risk: -0.3 },
          { label: '100–149 mg/dL — Borderline', value: 'borderline', risk: 0.5 },
          { label: '150–199 mg/dL — Elevated', value: 'elevated', risk: 1 },
          { label: '200+ mg/dL — High', value: 'high', risk: 2 },
          { label: 'I don\'t know', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'waistChange',
        label: 'Waist size change over the past 12 months',
        type: 'radio',
        options: [
          { label: 'Decreased — lost abdominal fat', value: 3, risk: -0.5 },
          { label: 'Stable — no change', value: 2, risk: 0 },
          { label: 'Slightly increased — 1–2 inches', value: 1, risk: 0.8 },
          { label: 'Significantly increased — 3+ inches', value: 0, risk: 2 },
        ],
      },
      {
        id: 'weightChange',
        label: 'Weight change over the past 12 months',
        type: 'radio',
        options: [
          { label: 'Intentionally lost weight and maintained', value: 5, risk: -0.5 },
          { label: 'Stable — within 5 lbs', value: 4, risk: 0 },
          { label: 'Gained 5–15 lbs unintentionally', value: 3, risk: 0.5 },
          { label: 'Gained 15+ lbs unintentionally', value: 2, risk: 1.5 },
          { label: 'Lost 10+ lbs unintentionally', value: 1, risk: 1, redFlag: true },
        ],
      },
      {
        id: 'cravings',
        label: 'Frequency of intense sugar or carbohydrate cravings',
        type: 'radio',
        options: [
          { label: 'Rarely or never', value: 4, risk: 0 },
          { label: 'Occasionally — a few times per week', value: 3, risk: 0.3 },
          { label: 'Daily', value: 2, risk: 0.8 },
          { label: 'Multiple times daily — difficult to resist', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'postMealFatigue',
        label: 'Post-meal fatigue or brain fog',
        type: 'radio',
        options: [
          { label: 'Never', value: 4, risk: 0 },
          { label: 'Occasionally', value: 3, risk: 0.3 },
          { label: 'Frequently — most meals', value: 2, risk: 1 },
          { label: 'Almost always — significantly impairs my afternoon', value: 1, risk: 2 },
        ],
      },
    ],
  },

  // ── 9. CARDIOVASCULAR PERFORMANCE ─────────────────────────────────────
  {
    id: 'cardiovascular',
    icon: '◉',
    title: 'Cardiovascular Performance',
    subtitle: 'Functional and clinical markers of cardiovascular age',
    questions: [
      {
        id: 'stairTest',
        label: 'Can you climb 2 flights of stairs without stopping to rest?',
        type: 'radio',
        options: [
          { label: 'Yes — easily, no symptoms', value: 3, risk: 0 },
          { label: 'Yes — noticeably winded at the top', value: 2, risk: 0.5 },
          { label: 'I have to pause or stop midway', value: 1, risk: 1.5 },
          { label: 'No — I avoid stairs due to symptoms', value: 0, risk: 3, redFlag: true },
        ],
      },
      {
        id: 'exertionalSymptoms',
        label: 'During or after exertion — select any that apply',
        type: 'multiselect',
        options: [
          { value: 'Chest pain or pressure', label: 'Chest pain or pressure' },
          { value: 'Unusual shortness of breath', label: 'Unusual shortness of breath' },
          { value: 'Dizziness or lightheadedness', label: 'Dizziness or lightheadedness' },
          { value: 'Heart palpitations or irregular heartbeat', label: 'Heart palpitations or irregular heartbeat' },
          { value: 'Jaw, arm, or back pain with exertion', label: 'Jaw, arm, or back pain with exertion' },
          { value: 'Fainting or near-fainting', label: 'Fainting or near-fainting' },
          { value: 'None of the above', label: 'None of the above' },
        ],
        riskMap: {
          'Chest pain or pressure': 3,
          'Unusual shortness of breath': 2,
          'Dizziness or lightheadedness': 1.5,
          'Heart palpitations or irregular heartbeat': 1,
          'Jaw, arm, or back pain with exertion': 3,
          'Fainting or near-fainting': 2.5,
        },
        redFlagOptions: ['Chest pain or pressure', 'Jaw, arm, or back pain with exertion', 'Fainting or near-fainting'],
      },
      {
        id: 'coronaryCalcium',
        label: 'Coronary artery calcium (CAC) score — if tested',
        type: 'radio',
        options: [
          { label: '0 — No detectable calcium (very low risk)', value: 'zero', risk: -0.5 },
          { label: '1–100 — Mild', value: 'mild', risk: 1 },
          { label: '101–400 — Moderate', value: 'moderate', risk: 2 },
          { label: '400+ — Severe', value: 'severe', risk: 3.5 },
          { label: 'Not tested', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'knownApoB',
        label: 'Most recent ApoB or LDL (if known)',
        type: 'radio',
        options: [
          { label: 'ApoB <60 or LDL <70 — Optimal', value: 'optimal', risk: -0.3 },
          { label: 'ApoB 60–80 or LDL 70–100 — Good', value: 'good', risk: 0 },
          { label: 'ApoB 80–100 or LDL 100–130 — Borderline', value: 'borderline', risk: 0.8 },
          { label: 'ApoB 100+ or LDL 130+ — Elevated', value: 'elevated', risk: 1.5 },
          { label: 'I don\'t know', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'knownBloodPressure',
        label: 'Average blood pressure reading',
        type: 'radio',
        options: [
          { label: 'Under 115/75 — Optimal', value: 'optimal', risk: -0.3 },
          { label: '115–120 / 75–80 — Normal', value: 'normal', risk: 0 },
          { label: '121–129 / 80 — Elevated', value: 'elevated', risk: 0.5 },
          { label: '130–139 / 80–89 — Stage 1 hypertension', value: 'stage1', risk: 1.5 },
          { label: '140+ / 90+ — Stage 2 hypertension', value: 'stage2', risk: 2.5 },
          { label: 'I don\'t know', value: 'unknown', risk: 0 },
        ],
      },
      {
        id: 'vo2maxWearable',
        label: 'VO2 max estimate from wearable (if available)',
        type: 'radio',
        options: [
          { label: '55+ mL/kg/min — Superior / Elite', value: 'elite', risk: -1.5 },
          { label: '45–54 mL/kg/min — Excellent', value: 'excellent', risk: -0.5 },
          { label: '35–44 mL/kg/min — Good / Average', value: 'good', risk: 0.5 },
          { label: '25–34 mL/kg/min — Below average', value: 'below', risk: 1.5 },
          { label: 'Under 25 mL/kg/min — Poor', value: 'poor', risk: 3 },
          { label: 'Not available', value: 'unknown', risk: 0 },
        ],
      },
    ],
  },

  // ── 10. GUT & UROLOGICAL HEALTH ────────────────────────────────────────
  {
    id: 'gutUrological',
    icon: '◆',
    title: 'Gut & Urological Health',
    subtitle: 'Gut microbiome and urinary function — underappreciated aging markers',
    questions: [
      {
        id: 'bowelFrequency',
        label: 'Bowel movement frequency',
        type: 'radio',
        options: [
          { label: '1–3 times daily — Optimal', value: 'optimal', risk: 0 },
          { label: 'Once daily — Normal', value: 'normal', risk: 0 },
          { label: 'Every 2–3 days — Mild constipation', value: 'mild_c', risk: 0.5 },
          { label: 'Less than every 3 days — Chronic constipation', value: 'chronic_c', risk: 1.5 },
          { label: '3+ times daily — Loose or frequent', value: 'frequent', risk: 0.8 },
        ],
      },
      {
        id: 'bristolScale',
        label: 'Stool consistency (Bristol Stool Scale)',
        type: 'radio',
        options: [
          { label: 'Type 3–4 — Well-formed, smooth sausage (Optimal)', value: 'optimal', risk: 0 },
          { label: 'Type 1–2 — Hard, lumpy, difficult to pass (Constipated)', value: 'constipated', risk: 1 },
          { label: 'Type 5–6 — Soft blobs or mushy (Loose)', value: 'loose', risk: 0.8 },
          { label: 'Type 7 — Entirely liquid (Diarrhea)', value: 'diarrhea', risk: 1.5 },
          { label: 'Varies significantly day to day', value: 'variable', risk: 0.8 },
        ],
      },
      {
        id: 'bloating',
        label: 'Frequency of significant bloating or abdominal discomfort',
        type: 'radio',
        options: [
          { label: 'Rarely or never', value: 4, risk: 0 },
          { label: 'Occasionally — once or twice a week', value: 3, risk: 0.3 },
          { label: 'Frequently — most days', value: 2, risk: 1 },
          { label: 'Daily and significantly disruptive', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'nocturia',
        label: 'Nightly wakening to urinate (nocturia)',
        type: 'radio',
        options: [
          { label: 'Never — sleep through the night', value: 4, risk: 0 },
          { label: 'Occasionally — once or twice per week', value: 3, risk: 0.3 },
          { label: 'Most nights — once per night', value: 2, risk: 0.8 },
          { label: 'Most nights — twice or more', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'urinaryUrgency',
        label: 'Daytime urinary urgency or frequency',
        type: 'radio',
        options: [
          { label: 'Normal — no urgency or excessive frequency', value: 4, risk: 0 },
          { label: 'Mild — occasional urgency', value: 3, risk: 0.3 },
          { label: 'Moderate — urgency affecting daily activities', value: 2, risk: 0.8 },
          { label: 'Significant — urgent, frequent, or leakage', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'acidReflux',
        label: 'Acid reflux or heartburn frequency',
        type: 'radio',
        options: [
          { label: 'Rarely or never', value: 4, risk: 0 },
          { label: 'Occasionally — a few times per month', value: 3, risk: 0.3 },
          { label: 'Weekly', value: 2, risk: 0.8 },
          { label: 'Daily — on medication for it', value: 1, risk: 1.5 },
        ],
      },
    ],
  },

  // ── 11. SLEEP ARCHITECTURE ─────────────────────────────────────────────
  {
    id: 'sleep',
    icon: '◎',
    title: 'Sleep Architecture',
    subtitle: 'The primary recovery system and a leading aging accelerant',
    questions: [
      {
        id: 'sleepHours',
        label: 'Average nightly sleep duration',
        type: 'radio',
        options: [
          { label: '9+ hours', value: '9plus', risk: 0.5 },
          { label: '7–9 hours — Optimal', value: 'optimal', risk: 0 },
          { label: '6–7 hours', value: '6to7', risk: 1 },
          { label: '5–6 hours', value: '5to6', risk: 2 },
          { label: 'Under 5 hours', value: 'under5', risk: 3 },
        ],
      },
      {
        id: 'sleepQuality',
        label: 'Overall sleep quality',
        type: 'radio',
        options: [
          { label: 'Excellent — wake refreshed consistently', value: 5, risk: 0 },
          { label: 'Good — mostly restful with occasional disruption', value: 4, risk: 0.5 },
          { label: 'Fair — often unrested in the morning', value: 3, risk: 1 },
          { label: 'Poor — difficulty falling or staying asleep', value: 2, risk: 1.5 },
          { label: 'Very poor — chronic insomnia', value: 1, risk: 2.5 },
        ],
      },
      {
        id: 'sleepConsistency',
        label: 'Sleep/wake schedule consistency',
        type: 'radio',
        options: [
          { label: 'Very consistent — within 30 minutes daily', value: 4, risk: 0 },
          { label: 'Mostly consistent — varies by ~1 hour', value: 3, risk: 0.3 },
          { label: 'Inconsistent — varies significantly on weekends', value: 2, risk: 0.8 },
          { label: 'Highly irregular', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'sleepApneaDx',
        label: 'Sleep apnea status',
        type: 'radio',
        options: [
          { label: 'No sleep apnea', value: 0, risk: 0 },
          { label: 'Suspected but undiagnosed', value: 1, risk: 1 },
          { label: 'Diagnosed, untreated', value: 2, risk: 2 },
          { label: 'Diagnosed, treated (CPAP / appliance)', value: 3, risk: 0.5 },
        ],
      },
      {
        id: 'sleepAids',
        label: 'Use of sleep aids',
        type: 'radio',
        options: [
          { label: 'None needed', value: 0, risk: 0 },
          { label: 'Occasionally — magnesium, melatonin, etc.', value: 1, risk: 0.2 },
          { label: 'Regularly — OTC medications', value: 2, risk: 0.8 },
          { label: 'Prescription sleep medications nightly', value: 3, risk: 1.5 },
        ],
      },
      {
        id: 'screenTimeBeforeBed',
        label: 'Screen time in the final hour before sleep',
        type: 'radio',
        options: [
          { label: 'None — I avoid screens before bed', value: 4, risk: 0 },
          { label: 'Minimal — phone only briefly', value: 3, risk: 0.3 },
          { label: 'Moderate — 30–60 min of screens', value: 2, risk: 0.8 },
          { label: 'Heavy — screens until I fall asleep', value: 1, risk: 1.5 },
        ],
      },
    ],
  },

  // ── 12. PHYSICAL PERFORMANCE ───────────────────────────────────────────
  {
    id: 'activity',
    icon: '◐',
    title: 'Physical Performance',
    subtitle: 'Movement patterns, aerobic capacity, and strength',
    questions: [
      {
        id: 'exerciseFreq',
        label: 'Intentional exercise days per week',
        type: 'radio',
        options: [
          { label: '6–7 days', value: 7, risk: -1 },
          { label: '4–5 days', value: 5, risk: -0.5 },
          { label: '2–3 days', value: 3, risk: 0.5 },
          { label: '1 day or less', value: 1, risk: 1.5 },
          { label: 'Rarely or never', value: 0, risk: 3 },
        ],
      },
      {
        id: 'exerciseType',
        label: 'Primary exercise modality',
        type: 'radio',
        options: [
          { label: 'Mixed — strength + cardio + mobility', value: 4, risk: -0.5 },
          { label: 'Primarily strength / resistance training', value: 3, risk: 0 },
          { label: 'Primarily cardiovascular training', value: 2, risk: 0 },
          { label: 'Low-intensity only (walking, light yoga)', value: 1, risk: 0.5 },
          { label: 'No structured exercise', value: 0, risk: 2 },
        ],
      },
      {
        id: 'sportParticipation',
        label: 'Regular sport participation (tennis, golf, basketball, swimming, cycling, martial arts, etc.)',
        type: 'radio',
        options: [
          { label: 'Yes — competitive or frequent recreational (weekly)', value: 3, risk: -0.5 },
          { label: 'Yes — occasional recreational (monthly)', value: 2, risk: -0.2 },
          { label: 'No — no sport participation', value: 1, risk: 0 },
        ],
      },
      {
        id: 'dailySteps',
        label: 'Average daily step count',
        type: 'radio',
        options: [
          { label: '10,000+', value: 4, risk: -0.5 },
          { label: '7,000–9,999', value: 3, risk: 0 },
          { label: '5,000–6,999', value: 2, risk: 0.5 },
          { label: '3,000–4,999', value: 1, risk: 1 },
          { label: 'Under 3,000', value: 0, risk: 2 },
        ],
      },
      {
        id: 'sittingHours',
        label: 'Sedentary hours per day (primarily sitting)',
        type: 'radio',
        options: [
          { label: 'Under 4 hours', value: 1, risk: 0 },
          { label: '4–6 hours', value: 2, risk: 0.3 },
          { label: '6–8 hours', value: 3, risk: 0.8 },
          { label: '8–10 hours', value: 4, risk: 1.5 },
          { label: '10+ hours', value: 5, risk: 2.5 },
        ],
      },
      {
        id: 'flexibility',
        label: 'Mobility and flexibility',
        type: 'radio',
        options: [
          { label: 'Excellent — full range of motion, no restrictions', value: 4, risk: 0 },
          { label: 'Good — minor tightness, no functional limitations', value: 3, risk: 0.3 },
          { label: 'Fair — noticeable stiffness affecting some movements', value: 2, risk: 0.8 },
          { label: 'Poor — restriction affecting daily function', value: 1, risk: 1.5 },
        ],
      },
    ],
  },

  // ── 13. RECOVERY & ACTIVE LIFESTYLE ────────────────────────────────────
  {
    id: 'recovery',
    icon: '◇',
    title: 'Recovery & Active Lifestyle',
    subtitle: 'Deliberate recovery practices with documented longevity data',
    questions: [
      {
        id: 'saunaUse',
        label: 'Sauna use (any type — traditional, infrared)',
        type: 'radio',
        options: [
          { label: '4+ sessions per week — High dose', value: 4, risk: -1 },
          { label: '2–3 sessions per week', value: 3, risk: -0.5 },
          { label: 'Weekly', value: 2, risk: -0.2 },
          { label: 'Occasionally — monthly or less', value: 1, risk: 0 },
          { label: 'Never', value: 0, risk: 0 },
        ],
      },
      {
        id: 'coldExposure',
        label: 'Deliberate cold exposure (cold plunge, cold shower, ice bath)',
        type: 'radio',
        options: [
          { label: 'Daily or near-daily', value: 4, risk: -0.5 },
          { label: 'Several times per week', value: 3, risk: -0.3 },
          { label: 'Weekly', value: 2, risk: -0.1 },
          { label: 'Occasionally', value: 1, risk: 0 },
          { label: 'Never', value: 0, risk: 0 },
        ],
      },
      {
        id: 'redLightTherapy',
        label: 'Red light / photobiomodulation therapy',
        type: 'radio',
        options: [
          { label: 'Regular use — 3+ times per week', value: 3, risk: -0.3 },
          { label: 'Occasional use — weekly or less', value: 2, risk: -0.1 },
          { label: 'Never', value: 1, risk: 0 },
        ],
      },
      {
        id: 'yogaPilates',
        label: 'Yoga or Pilates practice',
        type: 'radio',
        options: [
          { label: 'Regular — 3+ sessions per week', value: 4, risk: -0.5 },
          { label: 'Weekly — 1–2 sessions', value: 3, risk: -0.2 },
          { label: 'Occasionally — monthly', value: 2, risk: 0 },
          { label: 'Never', value: 1, risk: 0 },
        ],
      },
      {
        id: 'massageBodywork',
        label: 'Massage, bodywork, or manual therapy',
        type: 'radio',
        options: [
          { label: 'Regular — biweekly or more', value: 3, risk: -0.2 },
          { label: 'Monthly', value: 2, risk: -0.1 },
          { label: 'Rarely or never', value: 1, risk: 0 },
        ],
      },
      {
        id: 'meditationBreathwork',
        label: 'Meditation, breathwork, or structured mindfulness',
        type: 'radio',
        options: [
          { label: 'Daily practice — 10+ minutes', value: 4, risk: -0.5 },
          { label: 'Several times per week', value: 3, risk: -0.3 },
          { label: 'Occasionally', value: 2, risk: 0 },
          { label: 'Never', value: 1, risk: 0 },
        ],
      },
      {
        id: 'sleepOptimization',
        label: 'Active sleep optimization practices (sleep tracking, blackout shades, temperature control, etc.)',
        type: 'radio',
        options: [
          { label: 'Yes — multiple deliberate practices in place', value: 3, risk: -0.3 },
          { label: 'Some — a few practices', value: 2, risk: 0 },
          { label: 'None — I don\'t optimize my sleep environment', value: 1, risk: 0 },
        ],
      },
    ],
  },

  // ── 14. NUTRITIONAL PROFILE ────────────────────────────────────────────
  {
    id: 'nutrition',
    icon: '◈',
    title: 'Nutritional Profile',
    subtitle: 'Dietary quality, metabolic inputs, and supplement stack',
    questions: [
      {
        id: 'dietQuality',
        label: 'Overall dietary quality',
        type: 'radio',
        options: [
          { label: 'Excellent — whole foods, high protein, minimal processed', value: 5, risk: -0.5 },
          { label: 'Good — mostly whole foods, occasional indulgences', value: 4, risk: 0 },
          { label: 'Average — mix of whole and processed foods', value: 3, risk: 0.5 },
          { label: 'Below average — frequent fast food or ultra-processed', value: 2, risk: 1.5 },
          { label: 'Poor — primarily processed or highly irregular', value: 1, risk: 2.5 },
        ],
      },
      {
        id: 'sugarIntake',
        label: 'Frequency of added sugars or refined carbohydrates',
        type: 'radio',
        options: [
          { label: 'Rarely — intentionally minimized', value: 4, risk: 0 },
          { label: 'Occasionally — a few times per week', value: 3, risk: 0.3 },
          { label: 'Daily', value: 2, risk: 1 },
          { label: 'Multiple times daily', value: 1, risk: 2 },
        ],
      },
      {
        id: 'hydration',
        label: 'Daily water intake',
        type: 'radio',
        options: [
          { label: '80+ oz — Optimal', value: 4, risk: 0 },
          { label: '60–79 oz', value: 3, risk: 0.2 },
          { label: '40–59 oz', value: 2, risk: 0.5 },
          { label: 'Under 40 oz', value: 1, risk: 1 },
        ],
      },
      {
        id: 'proteinAdequacy',
        label: 'Estimated daily protein intake',
        type: 'radio',
        options: [
          { label: '0.7–1g per lb of body weight — tracked consistently', value: 3, risk: 0 },
          { label: 'Likely adequate — protein at most meals', value: 2, risk: 0.3 },
          { label: 'Uncertain — I don\'t track protein', value: 1, risk: 0.5 },
          { label: 'Low — my diet is protein-deficient', value: 0, risk: 1.5 },
        ],
      },
      {
        id: 'supplements',
        label: 'Supplements taken consistently — select all that apply',
        type: 'multiselect',
        options: [
          { value: 'Omega-3 / Fish Oil', label: 'Omega-3 / Fish Oil' },
          { value: 'Vitamin D3', label: 'Vitamin D3' },
          { value: 'Magnesium', label: 'Magnesium' },
          { value: 'NAD+ precursor (NMN/NR)', label: 'NAD+ precursor (NMN/NR)' },
          { value: 'Creatine', label: 'Creatine' },
          { value: 'Collagen / Collagen peptides', label: 'Collagen / Collagen peptides' },
          { value: 'Probiotics', label: 'Probiotics' },
          { value: 'Multivitamin', label: 'Multivitamin' },
          { value: 'B-complex', label: 'B-complex' },
          { value: 'Zinc', label: 'Zinc' },
          { value: 'Vitamin K2', label: 'Vitamin K2' },
          { value: 'CoQ10 / Ubiquinol', label: 'CoQ10 / Ubiquinol' },
          { value: 'Berberine', label: 'Berberine' },
          { value: 'Resveratrol / Quercetin', label: 'Resveratrol / Quercetin' },
          { value: 'Lion\'s Mane', label: 'Lion\'s Mane' },
          { value: 'Taurine', label: 'Taurine' },
          { value: 'Alpha-lipoic acid', label: 'Alpha-lipoic acid' },
          { value: 'TUDCA (liver support)', label: 'TUDCA (liver support)' },
          { value: 'Spermidine', label: 'Spermidine' },
          { value: 'Melatonin', label: 'Melatonin' },
          { value: 'Ashwagandha / Adaptogens', label: 'Ashwagandha / Adaptogens' },
          { value: 'Protein powder (daily)', label: 'Protein powder (daily)' },
          { value: 'Electrolytes (daily)', label: 'Electrolytes (daily)' },
          { value: 'None', label: 'None' },
        ],
      },
      {
        id: 'alcoholType',
        label: 'Primary alcohol consumption pattern (if applicable)',
        type: 'radio',
        options: [
          { label: 'I don\'t drink', value: 0, risk: 0 },
          { label: 'Light daily — 1 drink most evenings', value: 1, risk: 0.3 },
          { label: 'Moderate spread — a few drinks across the week', value: 2, risk: 0.2 },
          { label: 'Weekend concentration — most drinks on 1–2 days', value: 3, risk: 1 },
          { label: 'Binge pattern — 4+ drinks in a sitting regularly', value: 4, risk: 2 },
        ],
      },
    ],
  },

  // ── 15. STRESS & COGNITION ─────────────────────────────────────────────
  {
    id: 'stress',
    icon: '◉',
    title: 'Stress & Cognition',
    subtitle: 'Perceived stress, mental load, and cognitive performance',
    questions: [
      {
        id: 'stressLevel',
        label: 'Over the past month, how often have you felt unable to control important things in your life?',
        type: 'radio',
        options: [
          { label: 'Never', value: 0, risk: 0 },
          { label: 'Almost never', value: 1, risk: 0.3 },
          { label: 'Sometimes', value: 2, risk: 0.8 },
          { label: 'Fairly often', value: 3, risk: 1.5 },
          { label: 'Very often', value: 4, risk: 2.5 },
        ],
      },
      {
        id: 'burnout',
        label: 'Frequency of burnout or emotional exhaustion',
        type: 'radio',
        options: [
          { label: 'Rarely or never', value: 0, risk: 0 },
          { label: 'Occasionally — a few times per year', value: 1, risk: 0.5 },
          { label: 'Monthly', value: 2, risk: 1 },
          { label: 'Weekly', value: 3, risk: 2 },
          { label: 'Almost daily', value: 4, risk: 3 },
        ],
      },
      {
        id: 'cognitivePerformance',
        label: 'Current cognitive performance (focus, memory, mental clarity)',
        type: 'radio',
        options: [
          { label: 'Excellent — sharp, focused, minimal brain fog', value: 5, risk: 0 },
          { label: 'Good — occasional lapses, generally sharp', value: 4, risk: 0.3 },
          { label: 'Fair — noticeable fog or difficulty concentrating', value: 3, risk: 0.8 },
          { label: 'Poor — frequent brain fog or memory issues', value: 2, risk: 1.5 },
          { label: 'Significantly impaired', value: 1, risk: 2.5 },
        ],
      },
      {
        id: 'workHours',
        label: 'Average weekly work hours',
        type: 'radio',
        options: [
          { label: 'Under 40 hours', value: 1, risk: 0 },
          { label: '40–50 hours', value: 2, risk: 0.2 },
          { label: '50–60 hours', value: 3, risk: 0.5 },
          { label: '60–70 hours', value: 4, risk: 1 },
          { label: '70+ hours', value: 5, risk: 1.8 },
        ],
      },
      {
        id: 'mentalHealthSupport',
        label: 'Current use of mental health support or evidence-based tools',
        type: 'radio',
        options: [
          { label: 'Active therapy or structured program', value: 3, risk: -0.3 },
          { label: 'Occasionally as needed', value: 2, risk: 0 },
          { label: 'No — managing well without it', value: 1, risk: 0 },
          { label: 'No — and I feel I need support', value: 0, risk: 0.5 },
        ],
      },
    ],
  },

  // ── 16. LIFESTYLE FACTORS ──────────────────────────────────────────────
  {
    id: 'lifestyle',
    icon: '◆',
    title: 'Lifestyle Factors',
    subtitle: 'Substance use, social health, oral health, and preventive care',
    questions: [
      {
        id: 'smoking',
        label: 'Tobacco / nicotine use',
        type: 'radio',
        options: [
          { label: 'Never smoker', value: 0, risk: 0 },
          { label: 'Former — quit 5+ years ago', value: 1, risk: 0.5 },
          { label: 'Former — quit within 5 years', value: 2, risk: 2 },
          { label: 'Current — occasional', value: 3, risk: 3 },
          { label: 'Current — daily', value: 4, risk: 5 },
          { label: 'Nicotine products (vape, pouches) — regular', value: 5, risk: 1.5 },
        ],
      },
      {
        id: 'alcoholWeekly',
        label: 'Average weekly alcoholic drinks',
        type: 'radio',
        options: [
          { label: 'None', value: 0, risk: 0 },
          { label: '1–3 drinks', value: 1, risk: 0 },
          { label: '4–7 drinks', value: 2, risk: 0.5 },
          { label: '8–14 drinks', value: 3, risk: 1.5 },
          { label: '15+ drinks', value: 4, risk: 3 },
        ],
      },
      {
        id: 'socialConnection',
        label: 'Quality of social relationships and support network',
        type: 'radio',
        options: [
          { label: 'Strong — deep, meaningful relationships', value: 4, risk: 0 },
          { label: 'Good — adequate connection, some close relationships', value: 3, risk: 0.3 },
          { label: 'Limited — few close connections, often feel alone', value: 2, risk: 1 },
          { label: 'Isolated — minimal meaningful social interaction', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'purposeScore',
        label: 'Sense of purpose or meaning in life',
        type: 'radio',
        options: [
          { label: 'Strong — clear direction and meaning', value: 4, risk: 0 },
          { label: 'Generally yes — mostly aligned with values', value: 3, risk: 0.2 },
          { label: 'Uncertain — searching or unclear', value: 2, risk: 0.5 },
          { label: 'No — feeling lost or without direction', value: 1, risk: 1 },
        ],
      },
      {
        id: 'dentalHealth',
        label: 'Oral health and flossing frequency (periodontal disease is an independent cardiovascular risk factor)',
        type: 'radio',
        options: [
          { label: 'Excellent — daily flossing, regular cleanings, no gum issues', value: 4, risk: 0 },
          { label: 'Good — occasional flossing, annual cleanings', value: 3, risk: 0.3 },
          { label: 'Fair — rarely floss, overdue for cleaning', value: 2, risk: 0.8 },
          { label: 'Poor — gum disease, bleeding gums, or significant dental issues', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'lastPhysical',
        label: 'Most recent comprehensive physical exam',
        type: 'radio',
        options: [
          { label: 'Within the last year', value: 3, risk: 0 },
          { label: '1–2 years ago', value: 2, risk: 0.3 },
          { label: '3–5 years ago', value: 1, risk: 0.8 },
          { label: '5+ years ago or never', value: 0, risk: 1.5 },
        ],
      },
      {
        id: 'dexaScan',
        label: 'DEXA bone density scan (recommended for women 65+, earlier if risk factors)',
        type: 'radio',
        options: [
          { label: 'Up to date — normal bone density', value: 'normal', risk: 0 },
          { label: 'Up to date — osteopenia found', value: 'osteopenia', risk: 0.8 },
          { label: 'Not done — eligible or overdue', value: 'overdue', risk: 0.5 },
          { label: 'Not yet indicated by age', value: 'na', risk: 0 },
        ],
      },
      {
        id: 'environmentalExposure',
        label: 'Environmental exposures (air quality, toxin or chemical contact)',
        type: 'radio',
        options: [
          { label: 'Minimal — clean environment, toxin-conscious', value: 3, risk: 0 },
          { label: 'Moderate — typical urban / suburban exposure', value: 2, risk: 0.5 },
          { label: 'High — regular exposure to pollutants or chemicals', value: 1, risk: 1.5 },
        ],
      },
    ],
  },

  // ── 17. WEARABLE & DEVICE DATA ─────────────────────────────────────────
  {
    id: 'wearable',
    icon: '◎',
    title: 'Wearable & Device Data',
    subtitle: 'Objective biometric data from tracking devices',
    questions: [
      {
        id: 'wearableDevice',
        label: 'Health tracking wearable in use',
        type: 'radio',
        options: [
          { label: 'Oura Ring', value: 'oura', risk: 0 },
          { label: 'WHOOP', value: 'whoop', risk: 0 },
          { label: 'Apple Watch', value: 'apple', risk: 0 },
          { label: 'Garmin', value: 'garmin', risk: 0 },
          { label: 'Continuous glucose monitor (CGM)', value: 'cgm', risk: 0 },
          { label: 'Other fitness tracker', value: 'other', risk: 0 },
          { label: 'No wearable', value: 'none', risk: 0 },
        ],
      },
      {
        id: 'hrvScore',
        label: 'Average HRV (Heart Rate Variability) — if known',
        type: 'radio',
        options: [
          { label: '80+ ms — Excellent', value: 5, risk: -1 },
          { label: '60–79 ms — Good', value: 4, risk: -0.5 },
          { label: '40–59 ms — Average', value: 3, risk: 0.5 },
          { label: '20–39 ms — Below average', value: 2, risk: 1.5 },
          { label: 'Under 20 ms — Poor', value: 1, risk: 2.5 },
          { label: 'Unknown', value: 0, risk: 0 },
        ],
      },
      {
        id: 'restingHR',
        label: 'Resting heart rate',
        type: 'radio',
        options: [
          { label: 'Under 50 bpm — Athletic', value: 5, risk: -1 },
          { label: '50–60 bpm — Excellent', value: 4, risk: -0.5 },
          { label: '61–70 bpm — Good', value: 3, risk: 0 },
          { label: '71–80 bpm — Average', value: 2, risk: 0.8 },
          { label: '81–90 bpm — Elevated', value: 1, risk: 1.5 },
          { label: '90+ bpm — High', value: 0, risk: 2.5 },
        ],
      },
      {
        id: 'oxygenSat',
        label: 'Average SpO2 from wearable',
        type: 'radio',
        options: [
          { label: '97–100% — Optimal', value: 4, risk: 0 },
          { label: '95–96% — Normal', value: 3, risk: 0.3 },
          { label: '93–94% — Low normal', value: 2, risk: 0.8 },
          { label: 'Below 93% — Concerning', value: 1, risk: 2, redFlag: true },
          { label: 'Unknown', value: 0, risk: 0 },
        ],
      },
      {
        id: 'cgmData',
        label: 'If using a CGM — average glucose / time in range',
        type: 'radio',
        options: [
          { label: 'Average glucose <100 mg/dL, >90% time in range — Excellent', value: 'excellent', risk: -0.5 },
          { label: 'Average glucose 100–110, 80–90% time in range — Good', value: 'good', risk: 0 },
          { label: 'Average glucose 110–125, 70–80% time in range — Borderline', value: 'borderline', risk: 1 },
          { label: 'Average glucose 125+ or <70% time in range — Elevated', value: 'elevated', risk: 2 },
          { label: 'Not using CGM', value: 'none', risk: 0 },
        ],
      },
    ],
  },

  // ── 18. SYMPTOM INVENTORY ──────────────────────────────────────────────
  {
    id: 'symptoms',
    icon: '◐',
    title: 'Symptom Inventory',
    subtitle: 'Functional indicators of biological age',
    questions: [
      {
        id: 'energyLevel',
        label: 'Typical daily energy levels',
        type: 'radio',
        options: [
          { label: 'High and consistent throughout the day', value: 5, risk: 0 },
          { label: 'Good morning, mild afternoon dip', value: 4, risk: 0.3 },
          { label: 'Moderate — noticeable fatigue by midday', value: 3, risk: 0.8 },
          { label: 'Low — persistent fatigue most of the day', value: 2, risk: 1.5 },
          { label: 'Severe — exhausted, barely functional', value: 1, risk: 2.5, redFlag: true },
        ],
      },
      {
        id: 'recoverySpeed',
        label: 'Recovery speed from physical exertion or illness',
        type: 'radio',
        options: [
          { label: 'Fast — back to baseline within 24–48 hours', value: 4, risk: 0 },
          { label: 'Moderate — 3–4 days', value: 3, risk: 0.5 },
          { label: 'Slow — a week or more', value: 2, risk: 1 },
          { label: 'Very slow — prolonged, significantly impairs function', value: 1, risk: 2 },
        ],
      },
      {
        id: 'jointPain',
        label: 'Joint pain, stiffness, or inflammation',
        type: 'radio',
        options: [
          { label: 'None', value: 0, risk: 0 },
          { label: 'Occasional mild discomfort', value: 1, risk: 0.3 },
          { label: 'Regular discomfort affecting some activities', value: 2, risk: 0.8 },
          { label: 'Significant pain affecting daily function', value: 3, risk: 1.5 },
        ],
      },
      {
        id: 'digestion',
        label: 'Digestive health overall',
        type: 'radio',
        options: [
          { label: 'Excellent — comfortable, regular, no concerns', value: 4, risk: 0 },
          { label: 'Good — occasional minor issues', value: 3, risk: 0.3 },
          { label: 'Fair — bloating, irregularity, or discomfort regularly', value: 2, risk: 0.8 },
          { label: 'Poor — chronic digestive issues', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'skinHairNail',
        label: 'Condition of skin, hair, and nails',
        type: 'radio',
        options: [
          { label: 'Excellent — healthy, vibrant', value: 4, risk: 0 },
          { label: 'Good — minor concerns only', value: 3, risk: 0.3 },
          { label: 'Fair — noticeable changes (dullness, thinning, brittleness)', value: 2, risk: 0.8 },
          { label: 'Poor — significant deterioration', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'libido',
        label: 'Libido / sexual health change over the past year',
        type: 'radio',
        options: [
          { label: 'Strong — no change or improvement', value: 4, risk: 0 },
          { label: 'Mild decline', value: 3, risk: 0.5 },
          { label: 'Moderate decline — noticeably reduced', value: 2, risk: 1 },
          { label: 'Significant decline', value: 1, risk: 1.5 },
        ],
      },
      {
        id: 'memoryChanges',
        label: 'Subjective memory or word-finding changes over the past year',
        type: 'radio',
        options: [
          { label: 'None — memory feels the same or better', value: 4, risk: 0 },
          { label: 'Occasional lapses — normal aging', value: 3, risk: 0.3 },
          { label: 'Noticeable change — affects daily function occasionally', value: 2, risk: 1 },
          { label: 'Significant — frequently affects daily function', value: 1, risk: 2 },
        ],
      },
    ],
  },

  // ── 19. SAFETY SCREENING (RED FLAGS) ──────────────────────────────────
  {
    id: 'redFlags',
    icon: '⚠',
    title: 'Safety Screening',
    subtitle: 'Required for clinical safety — 30 seconds',
    questions: [
      {
        id: 'chestPain',
        isRedFlag: true,
        type: 'radio',
        label: 'Are you currently experiencing chest pain, pressure, or tightness at rest or with minimal activity?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'severeSob',
        isRedFlag: true,
        type: 'radio',
        label: 'Are you experiencing severe shortness of breath at rest or that woke you from sleep?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'spo2Low',
        isRedFlag: true,
        type: 'radio',
        label: 'Has your SpO2 measured below 90% recently?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes or unsure', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'blackStools',
        isRedFlag: true,
        type: 'radio',
        label: 'Have you noticed black, tarry, or bloody stools recently?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'fainting',
        isRedFlag: true,
        type: 'radio',
        label: 'Have you fainted or lost consciousness in the past 30 days (without an obvious benign cause)?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'suicidalThoughts',
        isRedFlag: true,
        type: 'radio',
        label: 'Are you currently experiencing thoughts of self-harm or suicide?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'unexplainedWeightLoss',
        isRedFlag: true,
        type: 'radio',
        label: 'Have you experienced unexplained weight loss of 10+ lbs in the past 3 months?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
      {
        id: 'severeFatigue',
        isRedFlag: true,
        type: 'radio',
        label: 'Are you experiencing severe fatigue that is new, sudden in onset, or significantly limiting your daily function?',
        options: [
          { label: 'No', value: 'no', redFlag: false },
          { label: 'Yes', value: 'yes', redFlag: true },
        ],
      },
    ],
  },
];
