[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build -w packages/shared && npm run build -w apps/api"]

[start]
cmd = "node apps/api/dist/index.js"
